### ISSUE TITLE
ERROR: drlinfluids is not a valid editable requirement.

### ISSUE THREAD

**Issue by jiangzhangze** [venturi123/DRLinFluids#1]
Thank you for sharing such a good repository.
I failed when I install DRLinFluids from source code，here are the imformations I had met：
`ERROR: drlinfluids is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).`
And pip can't find a version that satisfies the requirement drlinfluids when I use `pip install drlinfluids` to install it.
I use WSL2 ,Ubuntu20.04 LTS,python3.10.0 and openfoam8.

**Comment by venturi123** [comment]
Hi @jiangzhangze ,

Thanks for the feedback on using DRLinFluids. We will do a rapid test of your question. 

Additionally, I wonder if you could successfully run the [docker or singularity container](https://github.com/venturi123/DRLinFluids-examples) on WSL2? Because I also encountered some weird problems when using WSL before.

**Comment by jiangzhangze** [comment]
Hi @venturi123 , 
I try it in docker a moment ago，and I got following error when I run  `python launch_multiprocessing_traning_cylinder.py`:

Traceback (most recent call last):
  File "launch_multiprocessing_traning_cylinder.py", line 99, in <module>
    evaluation_environment = environments.pop()
IndexError: pop from empty list

**Comment by 1900360** [comment]
Hi @jiangzhangze ,
I have met this question before. You can run the cylinder case in cylinder2D_multiprocessing folder, and the code is:
> python DRLinFluids_cylinder/launch_multiprocessing_traning_cylinder.py
When you run launch_multiprocessing_traning_cylinder.py in the DRLinFluids_cylinder folder, it will not detect the location of the envs file and will not be able to train.

**Comment by jiangzhangze** [comment]
Hi @venturi123 
Unfortunatly，I meet another problem： 
`subprocess.CalledProcessError: Command 'cd /DRLinfluids/cylinder2D_multiprocessing/env01 && reconstructPar > /dev/null' returned non-zero exit status 1.`😂

**Comment by 1900360** [comment]
Hi @jiangzhangze ,
Could you give us more details about this error? The docker is running fine in my computer.
Or maybe you can try singularity by our order.

**Comment by jiangzhangze** [comment]
Hi @venturi123 
Looks like I solved the problem，I run it as a root user at first.It runs normally up to now.

**Comment by 1900360** [comment]
That's fine, I will close this error

**Comment by jerabaul29** [comment]
Great that this is solved :) . @venturi123 @1900360 do you think it would be possible to update the Readme / instructions with the docker instructions? :)

**Comment by venturi123** [comment]
The README has been updated. Please see https://github.com/venturi123/DRLinFluids-examples/commit/9f9d75e094ff31b873a32150805e441e41ce83a8 for details.

Thanks for your kind reminder! @jerabaul29
