### ISSUE TITLE
How to have the history of drag coefficient

### ISSUE THREAD

**Issue by Yiphta-lab** [venturi123/DRLinFluids#16]
Good morning

Thank you very much for your work
Please I want to know how I can access to the evolution of drag  in the way it is present in your paper  after the simulation.

I reproduced the simulation but I don't know in which folder the history of drag is located

Can you help me?

Thank you very much 

Constantini

**Comment by venturi123** [comment]
Hi @Yiphta-lab ,

Thx for your interest in our work.

If I understand correctly, do you mean the drag curve along the time dimension? You can find all of them under the `record` folder for each environment.

**Comment by Yiphta-lab** [comment]
Ok I understand 

Thank you very much 

Me and my collaborator, we have so many question about the code
can we have a google sheet ou zoom call?
Please

**Comment by Yiphta-lab** [comment]
So we need a complete understanding of your code please. Is the reason why we want to take a zoom meeting with you

**Comment by venturi123** [comment]
Hi Yiphta,

Great to hear you're interested in teaming up with us. Before we dive into the details and set up a meeting, could you shoot me an email at qlwang@connect.hku.hk with some info about your research group and what projects you guys are working on? This will help us figure out how we can best work together and make our chat even more meaningful.

Qiulei

**Comment by Yiphta-lab** [comment]
Hello Qiulei,

I hope you are doing well.

I am working on topological data analysis for turbulent flows, and I am part of the M2N team ( https://lasie.univ-larochelle.fr/E1-M2N).

To be honest, I don't have clear ideas yet for producing an article, and I am still evaluating the potential of the developed code. I'm trying to understand how it works.

By the way, I followed the tutorial in the Readme. When I plot the drag curve against non-dimensional time (extracted from the 3rd column of the best_history_coef.csv file), it doesn't seem similar to the one presented in the article.

Is this normal?


Constantini

**Comment by venturi123** [comment]
Hey Constantini,

Could you send over the drag curve against the non-dimensional time you mentioned? Need to see that before I can give you a solid answer.

On the topic of topological data analysis for turbulent flows, I gotta say it's not really my area. But, I can definitely share some basics on how DRL is being used in CFD. Think of DRL as a kind of optimal control problem solver. If you can frame your physical problem that way, the DRLinFluids framework might just be what you need.

Qiulei

**Comment by Yiphta-lab** [comment]
Hello Qiulei

I sent you the draw in this mail.   I was thinking that the draw will go down but when I plot . I saw that  It is sinusoidal

I don't change anything in the code so I don't understand  why the plot is not like in the article you publish

Constantini

**Comment by Yiphta-lab** [comment]
This is the draw

**Comment by Yiphta-lab** [comment]
Hello Qiulei,
 I hope you're doing well. My thesis supervisors are not convinced by the DRL approach, but I want to persuade them that it's a very good approach for optimal control. For this, I need to understand the code thoroughly. That's why I'm trying to have an interview with you to truly comprehend the code; otherwise, they won't allow me to explore this path. If a video call is suitable for you, could you please keep me informed?

I just want to understand how to reproduce the same results as those presented in the article

Constantini

**Comment by venturi123** [comment]
Hi Constantini,

I've just replied to your email. And I think the topic of our discussion is beyond the scoop of the issue. So I will close it now.
If you have further bugs or suggestions to report. Please open another one.

Qiulei
