### ISSUE TITLE
Problem about post processing

### ISSUE THREAD

**Issue by jiangzhangze** [venturi123/DRLinFluids#17]
I‘m trying to reproduce [this paper](https://doi.org/10.1063/5.0152777).And now I have finished the training.But only reward curve can be reported by tensorboard.what should I do to get the RMS of the lift coefficient and the the non-dimensional amplitude

**Comment by venturi123** [comment]
Hi Zhangze,

You can obtain all the results, including action, step reward, Cd, Cl, etc. from the `record `folder for each environment.

**Comment by jiangzhangze** [comment]
> Hi Zhangze,
> 
> You can obtain all the results, including action, step reward, Cd, Cl, etc. from the `record `folder for each environment.

Hi @venturi123 ，Thanks for your reply.Here are the `best_history_force_Coeffs_df` in my env01.It looks like only one step of data is recorded.But I want to record all data during trainning.Do you  have any advices？

[best_history_force_Coeffs_df.csv](https://github.com/venturi123/DRLinFluids/files/14735155/best_history_force_Coeffs_df.csv)

**Comment by venturi123** [comment]
If I understand correctly, do you wanna an entire log for all eposides and all steps during the training?

DRLinFluids will indeed record all details of the training stage but in a separate manner, which means you can find files like `history_force_Coeffs_df_*.csv` in the `record` directory. The suffix "*" implies the number of episodes.

The `best_history_force_Coeffs_df.csv` you attached only recorded the best performance of DRL agent eposide, which is for quick check in training stage.

**Comment by jiangzhangze** [comment]
> If I understand correctly, do you wanna an entire log for all eposides and all steps during the training?

Lastly，I would like to confirm what each item in the history_force_Coeffs_df_*.csv is. I think from left to right are time, reward, drag, lift, action,  amplitude.

**Comment by venturi123** [comment]
Not really. The `history_force_Coeffs_df_*.csv` logs the output of five force coefficients over time. In sequence:
1. simulation time: t
2. total moment coefficient: Cm
3. total drag coefficient: Cd
4. total lift coefficient: Cl
5. total front lift coefficient: Cl(f)
6. total rear lift coefficient: Cl(r)

**Comment by jiangzhangze** [comment]
> Not really. The `history_force_Coeffs_df_*.csv` logs the output of five force coefficients over time. In sequence:
> 
> 1. simulation time: t
> 2. total moment coefficient: Cm
> 3. total drag coefficient: Cd
> 4. total lift coefficient: Cl
> 5. total front lift coefficient: Cl(f)
> 6. total rear lift coefficient: Cl(r)

Thanks a lot！

**Comment by venturi123** [comment]
Sound good. I guess we have resolved your question. : )
The issue will be closed, but feel free to reopen it once you have more comments.

Best,
Qiulei

**Comment by jiangzhangze** [comment]
I met with another problem:
this is the reward reported by tensorboard
![Figure_1](https://github.com/venturi123/DRLinFluids/assets/99314760/aa90e958-d36a-4670-bb24-4a76098a151a)

and this is the reward reported by env01/total_reward.csv
![Figure_2](https://github.com/venturi123/DRLinFluids/assets/99314760/8cbed3df-7dad-427c-822d-35ea8573cc64)
Do you know why this situation occurs
