### ISSUE TITLE
"Question consultation" or "inquiry."

### ISSUE THREAD

**Issue by qzlkentomomota** [venturi123/DRLinFluids#19]
Hello, Blogger. Your work is amazing and I deeply admire what you have accomplished. I am a beginner and I would like to know why the reference area (Aref) in your square for the force coefficients in incompressible flow is set to 2.308194622e-3. Shouldn't it be equal to lref? Moreover, your reference length should theoretically be 0.05 if the Reynolds number is 100, right? Your explanation is very important to me, and I would greatly appreciate it. Thank you very much.

**Comment by venturi123** [comment]
No, the value `lRef=0.0508` is derived from many typical papers in simulations and experiments. You can refer to this [paper](https://doi-org.eproxy.lib.hku.hk/10.1016/j.energy.2017.11.153) and find a more similar setup in its references.

Regarding your second question, when handling a two-dimensional flow and calculating the force coefficients, it considers the height direction when integrating the force on our cylinder, if I remember correctly, even though the N-S equation does not account for it. If you check the mesh, you will find that multiplying the mesh height and reference length obtains `Aref`. 

Moreover, the Reynolds number is related to inflow velocity, reference length, and kinematic viscosity. A common practice is to adjust the reference length and inflow velocity to appropriate values and keep them constant while changing the viscosity to adjust the Reynolds number to a predetermined value. Please refer to this [paper](https://doi.org/10.1017/jfm.2019.62) for specific methods.

**Comment by venturi123** [comment]
It seems there are no more questions. I'll close the issue now.
