### ISSUE TITLE
Running code in test mode

### ISSUE THREAD

**Issue by MohamedASattar** [venturi123/DRLinFluids#20]
**Description:**

> After running your code from the multi-process training as explained in the README, I have some questions regarding the output results and the testing process.

**Steps to Reproduce:**

> Followed the steps in the README to run the multi-process training.
> Observed that the output results are saved in the `record` folder.

**Expected Behavior:**

> I expect to understand whether the data in the `record` folder can be used directly for post-processing. Additionally, I need guidance on how to run the code in test mode using the data saved in the `log` folder to ensure the agent's performance.

**Actual Behavior:**

> I tried to run the code in test mode using the data saved in the `log` folder but was unsuccessful.

**Additional Information:**

1. Can you confirm if the output results in the `record` folder are directly usable for post-processing?
2. If we need to delete the files after training and run the code in test mode using the data saved in the `log` folder, how can we achieve this?
3. Could you guide me on the required changes in the code, such as which parts should be uncommented or deleted to run the code in test mode?

Thank you for your assistance.

**Comment by venturi123** [comment]
Hi @MohamedASattar ,

There are some necessary pieces of information I would like to know first. Which example are you running?

The `record` folder is designed as a simple logger for recording the training process. All data are stored in CSV format and can be easily visualized using pandas and matplotlib. So, what do you mean by "used directly for post-processing"? If you want to show the evolution curves, yes, that's exactly what the folder is intended for.

Also, could you please clarify what you mean by "run the code in test mode using the data saved in the log folder"?

Please clarify the above questions so we can provide you with a more accurate solution.

Best regards,

**Comment by MohamedASattar** [comment]
The example i mean is the square 2D , for the cylinder example, i noticed that reward is not charging and when i monitor the velocity contours, i find that no flow come out from jets .
For the square, it worked well but what i mean is that, if i need to run it again with out waiting for a Large number of episodes as we already finished the training

What should i do ?

Also can i make changes and use for example a constant velocity for the jet instead of using the velocity profiles available in newbc folder , and if i think to use 1 jet for example to save energy, what will happen for zero net mass flux , is it will achieved .

**Comment by venturi123** [comment]
Hi @MohamedASattar ,

It's quite strange that the square 2D example is experiencing this issue. Are you saying that the reward is not being accumulated from single steps? Are you running the unmodified case from the repository without any changes?

Regarding your second question, the checkpoint is all you need. Please refer to the following resources for more details:
- [Tensorforce backend](https://tensorforce.readthedocs.io/en/latest/basics/features.html?#save-restore)
- [Tianshou backend](https://tianshou.org/en/stable/01_tutorials/07_cheatsheet.html#resume-training-process)

As for your last question, yes, you can achieve this scenario easily. If you want a constant jet velocity, you can set the boundary condition to `fixedValue` and let the DRL agent control the `value` to adjust the jet.

Best,

**Comment by MohamedASattar** [comment]
The example i mean is the square 2D , for the cylinder example, i noticed that reward is not charging and when i monitor the velocity contours , i find that no flow coming out from jets .
For the square, it worked well but what i mean is that, if i need to run it again with out waiting for a Large number of episodes as we already finished the training.
What should i do ?

Also if i need to use 1 jet only to save energy, is the zero net mass flux will achieved, or we must use 2 jets . 
Thanks for your support

**Comment by MohamedASattar** [comment]
Thank you for your response. I ran the simulation as it is, but it keeps giving a constant reward. When I copied the environment folder and opened it with paraFoam to check the jet output, I found no flow coming out from the jet.

Regarding the jet   velocity profile at the square example, it works when I use the jet configuration like this:
`JET4
{
    type incrementalJetUniVelocity;
    alpha 0.2;
    t0 0.0075;
    deltaT 0.00025;
    v0 (0 -2.6261127 0);
    v1 (0 -2.6736567 0);
    value uniform (0 -2.6261127 0);
}`

As you can see, the values change with time. I also attempted to follow your suggestion of using a fixed velocity for easier understanding of how values change with action. So, I configured it like this:
`JET4
{
    type fixedValue;
    value uniform (0 0 0);
}`

However, the velocity remains zero and the reward becomes constant. Is there something incorrect in my boundary conditions, or is there something else that needs to be considered?

**Comment by 1900360** [comment]
Hi @MohamedASattar ,

For your first question, I ran the simulation as is, and this is what it looks like when I check the jet velocity with ParaView:
<img width="577" alt="f7989fc47188034ea976c5a646f30b6" src="https://github.com/user-attachments/assets/11bf8910-6d06-45db-af52-f25743e547b8">

It is obvious that there is velocity variation in the jet. The jet boundary condition at this time is:
` JET4 { type incrementalJetUniVelocity; alpha 0.2; t0 0.0075; deltaT 0.00025; v0 (0 -2.6261127 0); v1 (0 -2.6736567 0); value uniform (0 -2.6261127 0); }`

When you use the following boundary condition, the DRL code needs to be modified to change the jet velocity:`JET4 { type fixedValue; value uniform (0 0 0); }`

Best regards,
